### PR TITLE
Story/101121296 picklefield

### PR DESCRIPTION
**Pull request by erickpeirson**
Ok, check this out, especially ``isisdata/tests/test_attribute.py``. Depending on what they're thinking, we could also implement some validation in the ``Attribute`` class based on the value of ``Attribute.type_controlled``, but maybe that's something for later.

### CODE REVIEW

**Comment by erickpeirson** [comment]
Oh, and I moved the models to an app (``isisdata``)

**Comment by jdamerow** [comment]
Ok, I think we were talking past each other. I though you wanted to be able to have different field types depending on the content, and was confused how that would work if all PickleFields are TextFields, but that wasn't what you were trying to do right? Can we have validators depending on content rather than fieldtype in Django?

**Comment by erickpeirson** [comment]
Haha, oops. What I was worried about was being able to store non-string values, and retrieve them with fidelity to their original data type. So, for example, to be able to save a ``datetime`` as Attribute.value, and retrieve it (e.g. in a view) as a ``datetime`` rather than a string.

**Comment by jdamerow** [comment]
ok, cool. problem solved :)

**Comment by erickpeirson** [comment]
Excellent. And what I meant with respect to validation was, for example, to ensure that an Attribute with ``type_controlled="publication_date"`` has a ``value`` of type ``datetime``. We'd have to set up some mechanism for defining those constraints. But probably an issue for another day.

**Pull request merged**
