### PR TITLE
Story/ISISCB-540: Introducing ``Dataset``

### PR DESCRIPTION
**Pull request by erickpeirson**
@jdamerow Sorry, chose the wrong base in the last one. what do you think?

### CODE REVIEW

**Comment by jdamerow** [comment]
wanna add 'edited by' right away? since we know that'll be necessary?

**Comment by erickpeirson** [comment]
Ah, ok -- I nested the datasets (see the last migration) -- So if the literal was "IsisCB (SPW ed.)" then there are two datasets: ``(2) IsisCB (SPW ed.)`` that ``belongs_to`` ``(1) IsisCB``. And then the citation ``belongs_to`` (2).

Does that make sense?

**Comment by jdamerow** [comment]
but since we have its own data model now, doesn't it make sense to provide a field to specify the editor?

**Comment by erickpeirson** [comment]
Sure, yes

**Comment by jdamerow** [comment]
even if it does create an extra subset in the migration

**Comment by erickpeirson** [comment]
Got it

**Comment by erickpeirson** [comment]
@jdamerow  Should editor be FK to User, or just CharField?

**Comment by erickpeirson** [comment]
@jdamerow Ok how now?

**Pull request merged**
