### PR TITLE
Story/iexp 342

### PR DESCRIPTION
**Pull request by crispzips**

### CODE REVIEW

**Comment by jdamerow** [comment]
I thought the plan was to create new templates for users to create their own citations and not give them access to the curation site?

**Comment by crispzips** [comment]
> I thought the plan was to create new templates for users to create their own citations and not give them access to the curation site?

Where the template would differ significantly from the curation version for staff, I created new templates so that the code wouldn't have to contain a bunch of checks about whether the user is staff or regular user. But where there was little to no difference in the template for the regular user I just used the curation template instead of having two copies of all the templates. If you want to use all new templates for the regular user I can do that. In the meantime, we can go through 346 because that's a much smaller project.

**Comment by jdamerow** [comment]
If I remember correctly, last time I talked to Stephen, we decided not to give anyone access to curation but have an extra portal/pages for that.

**Comment by crispzips** [comment]
> If I remember correctly, last time I talked to Stephen, we decided not to give anyone access to curation but have an extra portal/pages for that.

ok i'll do that

**Pull request closed without merging**
