### PR TITLE
Story/iexp 346

### PR DESCRIPTION
**Pull request by crispzips**

### CODE REVIEW

**Review by jdamerow — COMMENTED** [review]
I'm confused. The ticket says "Autogenerate Categories using Similar Citations" but the code looks like it's for letting any user create citations. Is that the wrong ticket number? And also, didn't we decide to separate curation from user generated citations and give it it's own pages and views? I still believe that it's a bad idea to let anyone login to curation to add new things. A separate portal would be a lot cleaner and more maintainable.

**Comment by crispzips** [comment]
> I'm confused. The ticket says "Autogenerate Categories using Similar Citations" but the code looks like it's for letting any user create citations. Is that the wrong ticket number? And also, didn't we decide to separate curation from user generated citations and give it it's own pages and views? I still believe that it's a bad idea to let anyone login to curation to add new things. A separate portal would be a lot cleaner and more maintainable.

Yeah I'm just now realizing that it was branched from the ticket for user generated citations. I need to separate it out. I'll get back to you.

**Comment by jdamerow** [comment]
couple of things:
- for some reason I don't have access to IEXP-346 on Jira, did you change the permission somehow?
- this was the story about giving any user the option to create new citations, right? Didn't we talk about creating completely new pages for this and not letting any user have access to the curation site? There shouldn't be any changes in the curation pages be necessary, but there are a bunch.

**Comment by crispzips** [comment]
I have no idea what happened to that ticket I haven't looked at the ticket or worked on the branch in months. It looks like the ticket has been deleted on Jira?
________________________________

**Comment by StephenPWeldon** [comment]
Hmm. I suppose I might have done something to it when looking at the
tickets the other day, but I don't think I deleted anything. Not
intentionally at any rate. It's unlikely that I would have monkeyed with
this ticket.

I was Zooming before Christmas with a scholar whom I had met at HSS who was
interested in possibly doing some programming for us, so I suggested that
he look at our code on GitHub. I showed him the Jira site, which he was
able to look at, but I didn't invite him to be a team member though.

**Comment by jdamerow** [comment]
Very weird, only you Stephen and me should have permissions to delete tickets. I can't find any trace of it (if I got any notification emails about it, they seem to be gone as well). In any case, I've created a replacement ticket and assigned it to you, Paul: https://upconsulting.atlassian.net/browse/IEXP-375

[IEXP-375]: https://upconsulting.atlassian.net/browse/IEXP-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Pull request closed without merging**
