### PR TITLE
[#101121296] Story/101121296 erick

### PR DESCRIPTION
**Pull request by erickpeirson**
See what you think of my changes, sorry if I went overboard. I focused on Citation, Authority, and Attribute, and added several abstract mixins to cut down on repetition. I also cut out several fields, based on Stephen's latest list of desired fields.

Three thoughts:
*  Having a single model for Authority seems potentially problematic. They have type-specific fields (e.g. last name, first name), and some functionality (e.g. claiming ones' own "person" record) may be difficult without separating things out into separate classes. I think we can keep the power of having an Authority class using multi-table inheritance.
* How will Attribute work with non-text data? E.g. what about publication dates? Presumably dates should be in ISO-8601, but CharField obviously won't provide validation for that, and we'll have to write a lot of code to support that in our views. Not sure I have an answer, just thinking about it.
* I don't see anything in their documentation about user- or admin-generated "tags" yet -- maybe we should chat about how user-generated content fits in?

### CODE REVIEW

**Comment by jdamerow** [comment]
Hm, I was thinking about subclassing authorities, but I would want to avoid that we have to amend the model every time they want to include a new authority type. Given that so far the only type specific field is "person" maybe we should just have a subclass for Person? And everything else is an Authority object?

Regarding the attribute class, we could have several subclasses (one for date, one for numbers, one for string) and then we could specify that e.g. type publication_date is a DateAttribute, or location is a LocationAttribute? The default could be String, so that a new type would work automatically. What do you think?

**Comment by erickpeirson** [comment]
Sure, we could start with Person and see how it goes. The nice thing about multi-table inheritance is that we can add subclasses later without writing any extra code (aside from the model itself). Just create a ForeignKey relation to the parent class, and then any subclass instance can be selected as a target.

About the Attributes: isn't the point of having a separate Attribute model that we don't have to hard-code the relationship types into the other models? So if we're doing things like ``publication_date = models.OneToOneField('Attribute')`` it kind of defeats the purpose? 

Another approach to the data type problem might be to [create a custom Field[(https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/) that stores values as plain text in the background, but also keeps track of the datatype, so that its [to_python](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.Field.to_python) method can yield an object of the correct type.

**Comment by erickpeirson** [comment]
Or just pickle (serialize) the object in ``value_to_string``, and deserialize in ``to_python``

**Comment by jdamerow** [comment]
but you have to specify the list of attributes for a citation/authority somewhere, right? couldn't we in the same spot specify its type, and depending on that use a different attribute? e.g. in AttributeMixin

attributes_string = models.ManyToManyField('StringAttribute')
attributes_date = models.ManyToManyField('DateAttribute')
# etc

and then in exepct block:
        except AttributeError as E:
            # Look for ``name`` among related Attributes.
if is string attribute do this
            queryset = self.attributes.filter(type_controlled=name)
if date attribute 
            queryset = self.attributes_date.filter(type_controlled=name)
            if queryset.count() == 1:
                return queryset[0].value
            elif querset.count() > 1:
                return [a.value for a in queryset]
            raise E 

or maybe have a naming convention for attributes? If it ends with date, it's a date, etc. Or am I too confused about how this is gonna work? Still a little jetlagged...

**Comment by jdamerow** [comment]
hm, looks like I screw up the formatting... sorry

**Comment by erickpeirson** [comment]
Since ``Citation`` and ``Authority`` subclass ``AttributeMixin`` they will inherit the ``attribute`` field. The problem with having separate fields like that is it makes the views more complex. What I was thinking was something like:

```python
class PickleField(models.TextField):
    def get_db_prep_save(self, value):
        """Serialize and save as text"""
        if value is None:
            return
        return pickle.dumps(value)

    def to_python(self, value):
        """Deserialize; yields object of original type"""
        return pickle.loads(value)


class Attribute(models.Model):
    ...
    value = PickleField()
```

**Comment by jdamerow** [comment]
ok, looks good. where would the definition for the type of field go?

Erick wrote:

**Pull request merged**
